
package net.pkhapps.fenix.aspsms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "ASPSMSX2HttpGet", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ASPSMSX2HttpGet {


    /**
     * Send Simple WAP Push. Multiple Recipients syntax: Recipient1:TRN1;Recipient2:TRN2;... <br>Returns StatusCode:Number
     *
     * @param wapDescription
     * @param flashingSMS
     * @param timeZone
     * @param urlBufferedMessageNotification
     * @param originator
     * @param affiliateId
     * @param userKey
     * @param password
     * @param wapURL
     * @param recipients
     * @param urlNonDeliveryNotification
     * @param deferredDeliveryTime
     * @param urlDeliveryNotification
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SimpleWAPPush")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String simpleWAPPush(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Recipients")
            String recipients,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "WapDescription")
            String wapDescription,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "WapURL")
            String wapURL,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DeferredDeliveryTime")
            String deferredDeliveryTime,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FlashingSMS")
            String flashingSMS,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TimeZone")
            String timeZone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLBufferedMessageNotification")
            String urlBufferedMessageNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLDeliveryNotification")
            String urlDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLNonDeliveryNotification")
            String urlNonDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AffiliateId")
            String affiliateId);

    /**
     * Send Text Messages. Multiple Recipients syntax: Recipient1;Recipient2;Recipient3... <br>Returns StatusCode:Number
     *
     * @param messageText
     * @param password
     * @param recipients
     * @param originator
     * @param userKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendSimpleTextSMS")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String sendSimpleTextSMS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Recipients")
            String recipients,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageText")
            String messageText);

    /**
     * Send Text Messages. Multiple Recipients syntax: Recipient1:TRN1;Recipient2:TRN2;... <br>Returns StatusCode:Number
     *
     * @param messageText
     * @param password
     * @param flashingSMS
     * @param recipients
     * @param timeZone
     * @param urlBufferedMessageNotification
     * @param originator
     * @param urlNonDeliveryNotification
     * @param affiliateId
     * @param userKey
     * @param deferredDeliveryTime
     * @param urlDeliveryNotification
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendTextSMS")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String sendTextSMS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Recipients")
            String recipients,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageText")
            String messageText,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DeferredDeliveryTime")
            String deferredDeliveryTime,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FlashingSMS")
            String flashingSMS,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TimeZone")
            String timeZone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLBufferedMessageNotification")
            String urlBufferedMessageNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLDeliveryNotification")
            String urlDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLNonDeliveryNotification")
            String urlNonDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AffiliateId")
            String affiliateId);

    /**
     * Send Unicode Messages. Multiple Recipients syntax: Recipient1:TRN1;Recipient2:TRN2;... <br>Returns StatusCode:Number
     *
     * @param messageText
     * @param password
     * @param flashingSMS
     * @param recipients
     * @param timeZone
     * @param urlBufferedMessageNotification
     * @param originator
     * @param urlNonDeliveryNotification
     * @param affiliateId
     * @param userKey
     * @param deferredDeliveryTime
     * @param urlDeliveryNotification
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendUnicodeSMS")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String sendUnicodeSMS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Recipients")
            String recipients,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageText")
            String messageText,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "DeferredDeliveryTime")
            String deferredDeliveryTime,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FlashingSMS")
            String flashingSMS,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TimeZone")
            String timeZone,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLBufferedMessageNotification")
            String urlBufferedMessageNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLDeliveryNotification")
            String urlDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLNonDeliveryNotification")
            String urlNonDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AffiliateId")
            String affiliateId);

    /**
     * Check available credits. <br>Returns StatusCode:Number or Credits:Count
     *
     * @param password
     * @param userKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CheckCredits")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String checkCredits(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password);

    /**
     * Send a originator unlock code to mobile phone. <br>Returns StatusCode:Number
     *
     * @param password
     * @param originator
     * @param userKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendOriginatorUnlockCode")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String sendOriginatorUnlockCode(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator);

    /**
     * Unlock Originator. <br>Returns StatusCode:Number
     *
     * @param originatorUnlockCode
     * @param password
     * @param originator
     * @param affiliateId
     * @param userKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "UnlockOriginator")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String unlockOriginator(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "OriginatorUnlockCode")
            String originatorUnlockCode,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AffiliateId")
            String affiliateId);

    /**
     * Check originator authorization. <br>Returns StatusCode:Number
     *
     * @param password
     * @param originator
     * @param userKey
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "CheckOriginatorAuthorization")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String checkOriginatorAuthorization(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator);

    /**
     * Verify/Check Security Token. <br>Returns StatusCode:Number
     *
     * @param password
     * @param phoneNumber
     * @param tokenReference
     * @param userKey
     * @param verificationCode
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "VerifyToken")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String verifyToken(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PhoneNumber")
            String phoneNumber,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TokenReference")
            String tokenReference,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "VerificationCode")
            String verificationCode);

    /**
     * Send Security Token to mobile recipient. Multiple Recipients syntax: Recipient1:TRN1;Recipient2:TRN2;... <br>Returns StatusCode:Number
     *
     * @param urlBufferedMessageNotification
     * @param tokenValidity
     * @param originator
     * @param affiliateId
     * @param userKey
     * @param tokenMask
     * @param verificationCode
     * @param password
     * @param recipients
     * @param tokenReference
     * @param tokenCaseSensitive
     * @param urlNonDeliveryNotification
     * @param messageData
     * @param urlDeliveryNotification
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "SendTokenSMS")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String sendTokenSMS(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Originator")
            String originator,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Recipients")
            String recipients,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MessageData")
            String messageData,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TokenReference")
            String tokenReference,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TokenValidity")
            String tokenValidity,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TokenMask")
            String tokenMask,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "VerificationCode")
            String verificationCode,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TokenCaseSensitive")
            String tokenCaseSensitive,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLBufferedMessageNotification")
            String urlBufferedMessageNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLDeliveryNotification")
            String urlDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "URLNonDeliveryNotification")
            String urlNonDeliveryNotification,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AffiliateId")
            String affiliateId);

    /**
     * Inquire Delivery Notifications. Multiple TransactionReferenceNumbers delimited by ;<br>Returns DeliveryNotifications or on error StatusCode:Number
     *
     * @param password
     * @param userKey
     * @param transactionReferenceNumbers
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "InquireDeliveryNotifications")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String inquireDeliveryNotifications(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserKey")
            String userKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Password")
            String password,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "TransactionReferenceNumbers")
            String transactionReferenceNumbers);

    /**
     * Get Description for StatusCode:Number
     *
     * @param statusCode
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "GetStatusCodeDescription")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String getStatusCodeDescription(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "StatusCode")
            String statusCode);

    /**
     * @return returns java.lang.String
     */
    @WebMethod(operationName = "VersionInfo")
    @WebResult(name = "string", targetNamespace = "https://webservice.aspsms.com/aspsmsx2.asmx", partName = "Body")
    public String versionInfo();

}
