CREATE TABLE contacts (
  id                 BIGINT       NOT NULL AUTO_INCREMENT,
  rev                BIGINT       NOT NULL,
  cell_phone         VARCHAR(255) NOT NULL,
  email              VARCHAR(255) NOT NULL,
  first_name         VARCHAR(255) NOT NULL,
  last_name          VARCHAR(255) NOT NULL,
  single_name        VARCHAR(255) NOT NULL,
  fire_department_id BIGINT       NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (fire_department_id) REFERENCES fire_departments (id)
)
  ENGINE InnoDB;

CREATE TABLE contact_communication_methods (
  contact_id BIGINT       NOT NULL,
  method     VARCHAR(255) NOT NULL,
  PRIMARY KEY (contact_id, method),
  FOREIGN KEY (contact_id) REFERENCES contacts (id)
)
  ENGINE InnoDB;

CREATE TABLE contact_groups (
  id                 BIGINT       NOT NULL AUTO_INCREMENT,
  rev                BIGINT       NOT NULL,
  group_name         VARCHAR(255) NOT NULL,
  fire_department_id BIGINT       NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (fire_department_id) REFERENCES fire_departments (id)
)
  ENGINE InnoDB;

CREATE TABLE contact_group_members (
  group_id  BIGINT NOT NULL,
  member_id BIGINT NOT NULL,
  PRIMARY KEY (group_id, member_id),
  FOREIGN KEY (group_id) REFERENCES contact_groups (id),
  FOREIGN KEY (member_id) REFERENCES contacts (id)
)
  ENGINE InnoDB;

/*
CREATE TABLE message_recipients (message_id BIGINT NOT NULL, details VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (message_id, details, name))
  CREATE TABLE message_states (id BIGINT generated BY DEFAULT AS identity, rev BIGINT NOT NULL, communication_method VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, ts TIMESTAMP NOT NULL, message_id BIGINT NOT NULL, PRIMARY KEY (id))
  CREATE TABLE messages (id BIGINT generated BY DEFAULT AS identity, rev BIGINT NOT NULL, message_text clob NOT NULL, fire_department_id BIGINT NOT NULL, PRIMARY KEY (id))
*/